## Foundry Configuration File
## Default definitions: https://github.com/gakonst/foundry/blob/b7917fa8491aedda4dd6db53fbb206ea233cd531/config/src/lib.rs#L782

## The Default Profile
[default]
## Sets the concrete solc version to use
## This overrides the `auto_detect_solc` value
solc_version = '0.8.12'
auto_detect_solc = false
## Increase optimizer_runs since we expect multicalls to be highly queried
optimizer = true
optimizer_runs = 10_000
## Fuzz more than the default 256
fuzz_runs = 1_000

## The below non-default profiles can be set with the FOUNDRY_PROFILE environment variable
## For example, to use the `hardhat` profile, set `FOUNDRY_PROFILE=hardhat`
[hardhat]
src = "contracts"
out = "artifacts"
libs = ["node_modules"]

## Extreme Fuzzing CI Profile :P
[ci]
solc_version = '0.8.11'
auto_detect_solc = false
optimizer = true
optimizer_runs = 10_000
fuzz_runs = 100_000